DROP DATABASE kellyclarkson;
CREATE DATABASE kellyclarkson;

-- DROP TABLE ATTACKERS;
-- DROP TABLE VICTIMS;

-- Create user
GRANT ALL ON *.* TO 'userTest'@'localhost' IDENTIFIED BY 'passwordTest';

-- Size of record: 255+39+16+100+32 = 442 bits
CREATE TABLE VICTIMS(
    SESSION_ID   CHAR(255) NOT NULL,
    IP          CHAR(39),
    PORT        SMALLINT UNSIGNED,
    HOST        VARCHAR(100),
    LAST_SEEN   DATETIME NOT NULL,
    CONSTRAINT PK_SESSION_ID PRIMARY KEY (SESSION_ID)
);

CREATE TABLE ATTACKERS(
    SESSION_ID   CHAR(255) NOT NULL,
    IP          CHAR(39),
    PORT        SMALLINT UNSIGNED,
    HOST        VARCHAR(100),
    LAST_SEEN   DATETIME NOT NULL,
    CONSTRAINT PK_SESSION_ID PRIMARY KEY (SESSION_ID)
);

CREATE TABLE UTILS(
    LAST_DELETION_OF_SESSIONS   DATETIME NOT NULL
);

INSERT INTO UTILS(LAST_DELETION_OF_SESSIONS) VALUES (NOW());
